package com.csc3202.lab.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseConnection {
    public static Connection connect() {
        String url = "jdbc:oracle:thin:@fsktmdbora.upm.edu.my:1521:FSKTM";
        String user = "B225759";
        String password = "225759"; // 替换为实际密码

        try {
            Connection connection = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the Oracle database!");

            // 初始化表
            createTables(connection);

            return connection;
        } catch (SQLException e) {
            System.err.println("Failed to connect to the database.");
            e.printStackTrace();
            return null;
        }
    }

    private static void createTables(Connection connection) {
        try (Statement stmt = connection.createStatement()) {
            // USERS 表
            String checkUsersTable = "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'USERS'";
            try (ResultSet rs = stmt.executeQuery(checkUsersTable)) {
                if (rs.next() && rs.getInt(1) == 0) {
                    String createUsersTable = """
                        CREATE TABLE USERS (
                            USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            USERNAME VARCHAR2(50) NOT NULL UNIQUE,
                            LOGIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    """;
                    stmt.execute(createUsersTable);
                    System.out.println("USERS table created successfully!");
                } else {
                    System.out.println("USERS table already exists.");
                }
            }

            // MESSAGES 表
            String checkMessagesTable = "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'MESSAGES'";
            try (ResultSet rs = stmt.executeQuery(checkMessagesTable)) {
                if (rs.next() && rs.getInt(1) == 0) {
                    String createMessagesTable = """
                        CREATE TABLE MESSAGES (
                            MESSAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            SENDER VARCHAR2(50) NOT NULL,
                            CONTENT CLOB NOT NULL,
                            TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    """;
                    stmt.execute(createMessagesTable);
                    System.out.println("MESSAGES table created successfully!");
                } else {
                    System.out.println("MESSAGES table already exists.");
                }
            }
        } catch (SQLException e) {
            System.err.println("Failed to create tables.");
            e.printStackTrace();
        }
    }
}
